openapi: "3.0.0"

info:
  version: 1.0.0
  title: Quisque API
  description: |
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nec dui nec nisl dapibus ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt vestibulum venenatis. Phasellus semper vehicula consectetur. Fusce convallis nulla id auctor interdum. Curabitur ut aliquam metus. Ut ac euismod elit.

    Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer auctor eu diam a convallis. Phasellus at maximus dui. Quisque imperdiet elementum volutpat. Integer molestie nisi hendrerit sem semper volutpat. Morbi nec porta eros. Morbi porttitor risus id massa convallis, at pharetra diam dictum.

    Nulla a nisl ullamcorper, scelerisque augue eu, suscipit massa. Vivamus consequat, nibh id porttitor rutrum, magna erat egestas ipsum, ac posuere neque lectus eu nibh. Etiam nunc tellus, lacinia eget luctus sit amet, rutrum et erat. Donec massa magna, finibus id vehicula vel, maximus sit amet mauris. Mauris pellentesque est a ex malesuada, a ultricies neque vulputate. Vivamus hendrerit felis a gravida tempor. Sed congue efficitur tellus, sed scelerisque lorem ultricies ac. Nullam aliquet facilisis tincidunt. Ut aliquam ipsum ac sem rutrum, ut vulputate elit porttitor.
  contact:
    name: Quisque support
    email: support@example.com
    url: https://example.com
  termsOfService: https://example.com/terms
  licence:
    name: MIT
    url: https://github.com/ouropencode/OpenDocumenter/blob/master/LICENSE
    identifier: MIT
    
servers:
  - url: https://fermentum.example.com
    description: Fermentum API
  - url: https://vestibulum.example.com
    description: Vestibulum API
    
externalDocs:
  url: https://doc.example.com
  description: Curabitur eget porta
  
tags:
  - name: Consectetur 
    description: |
      Pellentesque sit amet metus lacinia, venenatis erat quis, gravida massa. Suspendisse facilisis porttitor nunc, in consequat augue. Vestibulum tincidunt quam vel mi dapibus, non convallis lacus porttitor. Etiam id purus nec diam vehicula feugiat ut sit amet metus. Nunc mattis dolor nec tristique ullamcorper. Integer malesuada in nisl eu consequat. Donec eu quam pellentesque, sodales neque ut, mattis ipsum. Nullam sit amet varius est. Duis et commodo leo, non suscipit eros. Nam tempor ultricies libero in bibendum. Curabitur eu bibendum erat. Morbi odio ipsum, imperdiet quis luctus at, venenatis sit amet nibh.
  - name: Posuere
    description: |
      Cras condimentum pulvinar venenatis. Nam sed mi in odio ornare imperdiet et eget dolor. Curabitur eros lorem, eleifend id finibus et, euismod a felis. Aliquam lobortis consectetur nisl in faucibus. In euismod consequat justo, eu auctor nunc semper in. Cras non tristique sem. Duis nec luctus augue. Etiam leo leo, malesuada in pellentesque rutrum, tempus ut sem. Duis neque velit, aliquet at malesuada congue, ultricies vehicula lacus.
  - name: Egestas
    description: |
      Phasellus eu felis hendrerit, volutpat odio sit amet, luctus augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis tempor lectus. Nam eu enim malesuada ex tristique congue id id orci. Duis pretium nisi a arcu efficitur, quis faucibus justo suscipit. Mauris consequat, eros eget cursus scelerisque, sapien nibh sodales elit, ut porttitor nisi lacus nec ante. Suspendisse libero leo, pharetra vel porta nec, gravida eu magna. Vivamus sit amet nisl elementum, euismod justo quis, volutpat nunc.
  - name: Convallis
    description: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam pulvinar felis eget leo porta ultricies. Integer fermentum diam at ex commodo molestie. Nulla facilisi. Donec egestas metus sodales ante vulputate dignissim. Etiam ut sollicitudin ligula. Ut molestie leo nec nisl elementum mattis. Vestibulum sollicitudin tellus ut felis aliquam, a pulvinar ipsum tempus. Etiam ac faucibus arcu. Donec non lectus faucibus odio pulvinar tempus. Duis convallis dictum eros ut varius.

paths:
  /consectetur/venenatis:
    get:
      summary: Nullam vehicula enim
      description: |
        Nullam convallis leo tortor, at vestibulum libero hendrerit at. Vivamus posuere, velit eu consectetur commodo, lectus lorem dictum felis, at commodo sem nulla sed eros. Etiam in ligula non ligula condimentum rhoncus. Phasellus aliquam lacus nisl, non hendrerit magna accumsan et. Phasellus lacinia est quis faucibus fermentum. Nulla ac sem at massa vehicula porta ac laoreet ligula. Suspendisse lobortis molestie tincidunt. Sed faucibus neque at ex feugiat, ac consequat augue aliquam.
      tags:
        - Consectetur
      requestBody:
        required: true
        content:
          application/json:
            example:
              lorem: loremipsum
              ipsum: ipsumlorem
            schema:
              $ref: '#/components/schemas/LoremIpsum'
      responses:
        '200':
          description: Vestibulum vitae tempor lorem
          content:
            application/json:
              example:
                lorem: loremipsum
                ipsum: ipsumlorem
              schema:
                $ref: '#/components/schemas/LoremIpsum'
        '404':
          description: Nullam blandit faucibus vehicula
          content:
            application/json:
              example:
                error: iaculis arcu vitae urna accumsan
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Praesent vulputate vehicula urna
          content:
            application/json:
              example:
                error: scelerisque condimentum eleifend sed
              schema:
                $ref: '#/components/schemas/Error'
        '418':
          description: Nunc enim arcu mattis at rutrum
          content:
            application/json:
              example:
                error: arcu diam laoreet nulla in vestibulum
              schema:
                $ref: '#/components/schemas/Error'
        '428':
          description: Suspendisse accumsan a nulla
          content:
            application/json:
              example:
                error: mattis porta lorem eget tempor
              schema:
                $ref: '#/components/schemas/Error'
                
  /consectetur/vitae:
    post:
      summary: Phasellus nec vestibulum
      description: |
        Etiam aliquam quam ac porta venenatis. Nulla facilisi. Curabitur mollis finibus mi, et congue nisi tincidunt non. Sed eleifend justo et turpis mollis sodales. In et tortor in augue mattis congue. Vestibulum imperdiet imperdiet auctor. Quisque sit amet consequat justo, in imperdiet sapien. Integer hendrerit vehicula lacus, eget vestibulum nisi consequat eget. Morbi dapibus neque aliquam mauris lacinia venenatis. Sed facilisis libero lacus, in egestas massa scelerisque molestie. Nunc tincidunt gravida sem in gravida. Duis facilisis ultrices massa, a malesuada purus ultrices nec. Cras ac urna at nulla interdum efficitur. Sed eu arcu at ante consectetur imperdiet ut vel sem.
      tags:
        - Consectetur
      requestBody:
        required: true
        content:
          application/json:
            example:
              lorem: loremipsum
              ipsum: ipsumlorem
            schema:
              $ref: '#/components/schemas/LoremIpsum'
      responses:
        '200':
          description: Vestibulum vitae tempor lorem
          content:
            application/json:
              example:
                lorem: loremipsum
                ipsum: ipsumlorem
              schema:
                $ref: '#/components/schemas/LoremIpsum'
        '409':
          description: Nullam blandit faucibus vehicula
          content:
            application/json:
              example:
                error: curabitur sed lectus ac felis
              schema:
                $ref: '#/components/schemas/Error'

  /consectetur/pulvinar:
    put:
      summary: In tincidunt nec nisl sed ornare
      description: |
        Nullam blandit faucibus vehicula. Cras ut lectus ornare sapien euismod mollis id pharetra nulla. Aliquam a libero faucibus, posuere mi ac, blandit eros. Maecenas aliquet ultricies urna, nec laoreet lacus fermentum ut. Sed ac magna sed risus facilisis accumsan. Fusce scelerisque erat quis vestibulum varius. Quisque pretium interdum leo, a tristique turpis maximus eu.
      tags:
        - Consectetur
      requestBody:
        required: true
        content:
          application/json:
            example:
              lorem: loremipsum
              ipsum: ipsumlorem
            schema:
              $ref: '#/components/schemas/LoremIpsum'
      responses:
        '200':
          description: Nunc malesuada scelerisque sem
          content:
            application/json:
              example:
                lorem: loremipsum
                ipsum: ipsumlorem
              schema:
                $ref: '#/components/schemas/LoremIpsum'
        '409':
          description: Integer suscipit lacus lorem
          content:
            application/json:
              example:
                error: curabitur sed lectus ac felis
              schema:
                $ref: '#/components/schemas/Error'

  /consectetur/condimentum/dolor:
    delete:
      summary: Cras sed augue varius
      description: |
        Fringilla elit eget, tincidunt odio. Curabitur ultrices eget purus ut rutrum. Ut vulputate pulvinar finibus. Quisque sollicitudin velit non dui suscipit dapibus. Duis non porta nisi. Mauris et magna vitae felis imperdiet finibus. Fusce accumsan sed urna vitae vehicula. Nulla id fermentum orci. Aenean egestas ac libero at sodales. Nam in aliquam orci. Cras volutpat placerat arcu, in gravida magna pharetra at.
      tags:
        - Consectetur
      responses:
        '200':
          description: In ut facilisis nulla
          content:
            application/json:
              example:
                lorem: loremipsum
                ipsum: ipsumlorem
              schema:
                $ref: '#/components/schemas/LoremIpsum'
        '404':
          description: Aenean imperdiet nisi ac mauris
          content:
            application/json:
              example:
                error: integer leo massa
              schema:
                $ref: '#/components/schemas/Error'

  /posuere/mollis:
    get:
      summary: Praesent consectetur pharetra
      description: |
        Aenean a justo vel erat condimentum sollicitudin at ut velit. Mauris volutpat lectus lorem, sed rutrum felis cursus nec. Praesent dapibus, augue vitae varius viverra, ante orci gravida risus, eu aliquet ex est non metus. In ultricies sem ac dictum feugiat. Sed accumsan pretium justo vitae rutrum. Nunc in efficitur lacus. Proin sodales condimentum blandit. Maecenas consectetur accumsan vestibulum.
      tags:
        - Posuere
      responses:
        '200':
          description: Sed a porttitor risus id dapibus purus
          content:
            application/json:
              example:
                lorem: loremipsum
                ipsum: ipsumlorem
              schema:
                $ref: '#/components/schemas/LoremIpsum'

  /posuere/imperdiet:
    get:
      summary: Mauris volutpat lectus
      description: |
        This endpoint provides a list of all the teams the logged in user has access to.Praesent dapibus, augue vitae varius viverra, ante orci gravida risus, eu aliquet ex est non metus. In ultricies sem ac dictum feugiat. Sed accumsan pretium justo vitae rutrum. Nunc in efficitur lacus. Proin sodales condimentum blandit. Maecenas consectetur accumsan vestibulum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean facilisis lectus et rutrum sagittis.
      tags:
        - Posuere
      responses:
        '200':
          description: Sed a porttitor risus id dapibus purus
          content:
            application/json:
              example:
                lorem: loremipsum
                ipsum: ipsumlorem
              schema:
                $ref: '#/components/schemas/LoremIpsum'

  /egestas/{{lorem}}/aliquam:
    get:
      summary: Duis ac egestas augue
      description: |
        Pellentesque aliquet pulvinar tellus eu varius. Quisque ultrices sit amet augue tristique lobortis. Mauris id libero a nulla dignissim sodales. Vestibulum bibendum, nunc eu finibus imperdiet, magna libero ultrices dolor, eu ullamcorper urna ipsum fringilla libero. In venenatis odio a velit vestibulum fringilla. Phasellus vulputate bibendum porta. Duis mattis quis tellus nec posuere. Nunc rutrum pharetra vulputate. Praesent et metus ultrices, tristique mauris id, consectetur erat.
      tags:
        - Egestas
      responses:
        '200':
          description: Sed a porttitor risus id dapibus purus
          content:
            application/json:
              example:
                lorem: loremipsum
                ipsum: ipsumlorem
              schema:
                $ref: '#/components/schemas/LoremIpsum'
        '403':
          description: Nulla tincidunt dapibus nisi
          content:
            application/json:
              example:
                error: sit amet semper nibh
              schema:
                $ref: '#/components/schemas/Error'

  /convallis:
    post:
      summary: Vivamus eget leo eget
      description: |
        Etiam pellentesque ligula urna, quis feugiat ante rhoncus nec. Praesent egestas, mi a venenatis rutrum, nisl eros lacinia libero, eget consectetur lectus enim ac risus. Vivamus at eleifend justo. Mauris cursus orci lacinia vehicula vestibulum. Integer accumsan accumsan felis vel ultricies. Phasellus gravida imperdiet urna, et varius mi pharetra eu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi ut nunc lacinia, euismod elit non, fermentum est. Aliquam sollicitudin sodales velit quis ultricies. Nulla sollicitudin posuere magna, eu interdum ipsum aliquet in. Vestibulum cursus at lorem non faucibus. Aliquam erat volutpat. Proin sit amet arcu ullamcorper, elementum magna a, dictum leo. Nunc lobortis cursus lacus a condimentum.
      tags:
        - Convallis
      responses:
        '200':
          description: Quisque ultrices sit amet
          content:
            application/json:
              example:
                lorem: loremipsum
                ipsum: ipsumlorem
              schema:
                $ref: '#/components/schemas/LoremIpsum'

components:
  schemas:
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string

    LoremIpsum:
      type: object
      required:
        - lorem
        - ipsum
      properties:
        lorem:
          type: string
        ipsum:
          type: string